package mic.ontko;

//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Mon Apr 24 09:34:59 EDT 2000
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Mic1Symbol {
  /* terminals */
  static final int NOP = 38;
  static final int PC = 27;
  static final int EOL = 2;
  static final int address = 14;
  static final int DOTDEFAULT = 40;
  static final int SEMI = 13;
  static final int GOTO = 21;
  static final int Z = 23;
  static final int EOF = 0;
  static final int OPC = 32;
  static final int N = 22;
  static final int OR = 35;
  static final int ELSE = 20;
  static final int rd = 16;
  static final int wr = 17;
  static final int H = 33;
  static final int LV = 29;
  static final int label = 15;
  static final int error = 1;
  static final int MBR = 24;
  static final int fetch = 18;
  static final int MINUS = 4;
  static final int EIGHT = 7;
  static final int LPAREN = 11;
  static final int RPAREN = 12;
  static final int LESSTHAN = 8;
  static final int GREATERTHAN = 10;
  static final int IF = 19;
  static final int MDR = 26;
  static final int ZERO = 5;
  static final int TOS = 31;
  static final int MAR = 25;
  static final int AND = 36;
  static final int PLUS = 3;
  static final int CPP = 30;
  static final int DOTLABEL = 39;
  static final int SP = 28;
  static final int EQUALS = 9;
  static final int MBRU = 34;
  static final int ONE = 6;
  static final int NOT = 37;
}

